version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: postgres-lab
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: labdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d:ro
      - ./mock_data:/docker-entrypoint-initdb.d/mock_data:ro

volumes:
  postgres_data:
